#!/usr/bin/env bash
# A Bash script that loops indefinitely and reacts to SIGTERM

# Trap SIGTERM to display the message and continue
trap "echo 'echo I am invincible!!!' SIGTERM

while true; do
    echo "To infinity and beyond"
    # Use sleep in the background and wait so the trap is handled instantly
    sleep 2 &
    wait $!
done
