#!/usr/bin/env bash.
# This script provides information about a file named 'school'
# If file exists, perform further checks (nested logic)
else
\# If file does not exist
echo "$FILE file does not exist"
fi
